name: DevSecOps Pipeline
on: push

permissions:
  issues: write
  contents: read
  security-events: write # Permiso para guardar reportes de seguridad

jobs:
  construir-y-hackear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Construimos la imagen (pero NO la corremos todav√≠a)
      - name: Construir Imagen Docker
        run: docker build -t auditor:latest .

      # 2. AQU√ç EST√Å LO DIFERENTE: ¬°Escaneo de Seguridad!
      - name: Escanear vulnerabilidades con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'auditor:latest'
          format: 'table'
          exit-code: '0' # No romper el pipeline, solo avisar (pon 1 para ser estricto)
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # 3. Si sobrevivimos al escaneo, corremos el robot
      - name: Ejecutar Auditoria
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "üîí Imagen segura. Ejecutando monitor..."
          docker run -e GITHUB_TOKEN="$GITHUB_TOKEN" -e GITHUB_REPOSITORY="$GITHUB_REPOSITORY" auditor:latest