name: CI Pipeline Increible
on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ejecutar en Docker
        run: |
          docker build -t monitor-pro .
          docker run --name mi-contenedor monitor-pro
          docker cp mi-contenedor:/app/index.html .
      - name: Subir Reporte
        uses: actions/upload-artifact@v4
        with:
          name: mi-reporte-final
          path: index.html