name: DevSecOps Pipeline
on: push

permissions:
  issues: write
  contents: read
  security-events: write # Permiso para guardar reportes de seguridad

jobs:
  construir-y-hackear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Construir Imagen Docker
        run: docker build -t auditor:latest .

      - name: Escanear
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'auditor:latest'
          format: 'table'
          exit-code: '0' 
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Ejecutar Auditoria
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Ejecutando monitor..."
          docker run -e GITHUB_TOKEN="$GITHUB_TOKEN" -e GITHUB_REPOSITORY="$GITHUB_REPOSITORY" auditor:latest