name: CI Pipeline Profesional
on: 
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *' 

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Construir y ejecutar Docker
        run: |
          docker build -t monitor-pro .
          docker run --name mi-contenedor monitor-pro
          docker cp mi-contenedor:/app/index.html .

      - name: Subir Dashboard
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-profesional
          path: index.html